name: React Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    uses: ranydev0/github-actions/.github/workflows/github-pages-pipeline.yml@main
    secrets: inherit
